library(ggplot2)

#Load the data (i.e. \color{red}{\verb|read.csv()|}read.csv())

baseData <- read.csv("F:/TECHNOLOGY/Coursera/R/repdata_data_activity/activity.csv")

#Process/transform the data (if necessary) into a format suitable for your analysis

head(baseData)

dim(baseData)
summary(baseData)

# change date type to date class 
baseData$date <- as.Date(as.character(baseData$date))
# create NA logical vector
baseDataNA <- is.na(baseData$steps)
# create clean base for mean calculations
cleanBase <- baseData[!baseDataNA,]


#What is mean total number of steps taken per day?
# 1. Calculate the total number of steps taken per day


SummedDataByDay <- aggregate(baseData$steps, by=list(baseData$date), sum)
names(SummedDataByDay)[1] ="date"
names(SummedDataByDay)[2] ="totalsteps"
head(SummedDataByDay,15)

#2. Make a histogram of the total number of steps taken each day

ggplot(SummedDataByDay, aes(x = totalsteps)) +
  geom_histogram(fill = "steelblue", binwidth=1000) +
  labs(title = "Total Daily Steps", x = "Steps", y = "Frequency")


#3. Calculate and report the mean and median of the total number of steps taken per day
# Mean of steps taken per day
mean(SummedDataByDay$totalsteps,na.rm=TRUE)

#median of steps taken per day
median(SummedDataByDay$totalsteps,na.rm=TRUE)

#What is the average daily activity pattern?
#Make a time series plot (i.e. \color{red}{\verb|type = "l"|}type="l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)

nonNASubset <- baseData[!baseDataNA,]
MeanDataByInterval <- aggregate(nonNASubset$steps, by=list(nonNASubset$interval), mean)
# set the column names
names(MeanDataByInterval)[1] ="interval"
names(MeanDataByInterval)[2] ="steps"

ggplot(MeanDataByInterval, aes(x = interval, y=steps)) +
  labs(title = "Sum of Steps by Interval", x = "interval", y = "steps")+
  geom_line(color="red") 


#2. Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?

maxInterval <- MeanDataByInterval[which.max(MeanDataByInterval$steps),]
maxInterval


#Imputing missing values
#1. Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)

# generate listing of NA's
missingVals <- sum(baseDataNA)
missingVals


#2. Devise a strategy for filling in all of the missing values in the dataset. 
#3. Create a new dataset that is equal to the original dataset but with the missing data filled in.






# new dataset
baseData2 <- baseData
# NA's in dataset
# dataset minus NA's for Mean calculation
NABase2 <- baseData2[is.na(baseData2$steps),]
cleanBase2 <- baseData2[!is.na(baseData2$steps),]

# generate Mean Data2 by interval
MeanData2ByInterval <- aggregate(cleanBase2$steps, by=list(cleanBase2$interval), sum)
names(MeanData2ByInterval)[1] ="interval"
names(MeanData2ByInterval)[2] ="steps"

baseData2 <- baseData
missingData <- is.na(baseData2$steps)
meanVals <- tapply(cleanBase$steps, cleanBase$interval, mean, na.rm=TRUE, simplify=TRUE)
baseData2$steps[missingData] <- meanVals[as.character(baseData2$interval[missingData])]

# original missing data count
sum(missingData)



# count of NA values
sum(is.na(baseData2$steps))

FullSummedDataByDay <- aggregate(baseData2$steps, by=list(baseData2$date), sum)

names(FullSummedDataByDay)[1] ="date"
names(FullSummedDataByDay)[2] ="totalsteps"
head(FullSummedDataByDay,15)

# Plot using ggplot
ggplot(FullSummedDataByDay, aes(x = totalsteps)) +
  geom_histogram(fill = "steelblue", binwidth=1000) +
  labs(title = "Total Daily Steps", x = "Steps", y = "Frequency")

# Mean on New Data
mean(FullSummedDataByDay$totalsteps)

# Median on New Data
median(FullSummedDataByDay$totalsteps)


#Are there differences in activity patterns between weekdays and weekends?

baseData2$weekday <- weekdays(baseData2$date)
baseData2$weekend <- ifelse (baseData2$weekday == "Saturday" | baseData2$weekday == "Sunday", "Weekend", "Weekday")
#baseData2$weekend <- as.factor(baseData2$weekend)
head(baseData2,5)


MeanDataWeekendWeekday <- aggregate(baseData2$steps, by=list(baseData2$weekend, baseData2$interval), mean)
names(MeanDataWeekendWeekday)[1] ="weekend"
names(MeanDataWeekendWeekday)[2] ="interval"
names(MeanDataWeekendWeekday)[3] ="steps"

ggplot(MeanDataWeekendWeekday, aes(x = interval, y=steps, color=weekend)) +
  geom_line() +
  facet_grid(weekend ~ .) +
  labs(title = "Mean of Steps by Interval", x = "interval", y = "steps")
